"""Date utility functions."""
from datetime import datetime, timedelta
from typing import Tuple


def get_current_date_info() -> Tuple[str, str, str]:
    """
    Get current date information for pipeline generation.
    
    Returns:
        Tuple of (current_date_str, current_datetime_str, start_of_week_str)
        - current_date_str: YYYY-MM-DD format
        - current_datetime_str: ISO format with Z (UTC)
        - start_of_week_str: ISO format of Monday 00:00:00Z
    """
    current_date = datetime.utcnow()
    current_date_str = current_date.strftime("%Y-%m-%d")
    current_datetime_str = current_date.isoformat() + "Z"
    
    # Calculate start of week (Monday)
    days_since_monday = current_date.weekday()  # 0 = Monday, 6 = Sunday
    start_of_week = current_date.replace(hour=0, minute=0, second=0, microsecond=0)
    start_of_week = start_of_week - timedelta(days=days_since_monday)
    start_of_week_str = start_of_week.isoformat() + "Z"
    
    return current_date_str, current_datetime_str, start_of_week_str


def is_iso_date_string(value: str) -> bool:
    """Check if a string looks like an ISO date string."""
    # Pattern: YYYY-MM-DDTHH:mm:ssZ or YYYY-MM-DDTHH:mm:ss.sssZ
    # Also supports: YYYY-MM-DD HH:mm:ss+00:00 (space instead of T, with timezone)
    import re
    # Standard ISO format with T
    iso_pattern_t = r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})?$'
    # Format with space (generated by LLM sometimes)
    iso_pattern_space = r'^\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})?$'
    # Format with space and timezone: "YYYY-MM-DD HH:mm:ss+00:00"
    iso_pattern_space_tz = r'^\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}(\.\d+)?[+-]\d{2}:\d{2}$'
    return bool(re.match(iso_pattern_t, value) or re.match(iso_pattern_space, value) or re.match(iso_pattern_space_tz, value))


def parse_iso_date_string(date_str: str) -> datetime:
    """Parse ISO date string to datetime object."""
    # Normalize: replace space with T for ISO format
    if ' ' in date_str and 'T' not in date_str:
        date_str = date_str.replace(' ', 'T', 1)
    
    # Handle Z suffix (UTC)
    if date_str.endswith('Z'):
        date_str = date_str[:-1] + '+00:00'
    elif '+' not in date_str and '-' not in date_str[-6:] and 'Z' not in date_str:
        # Assume UTC if no timezone specified
        date_str = date_str + '+00:00'
    
    return datetime.fromisoformat(date_str.replace('Z', '+00:00'))

